#Expyriment 1.0.0 (Python 3.13.7), .xpe-file, coding: cp936
#date: Wed Sep 17 2025 21:57:53
#sha1: 758b4d
#modules: 
#display: size=(800, 600), window_mode=True, opengl=2
#os: uname_result(system='Windows', node='Shanli', release='11', version='10.0.26100', machine='AMD64')
Time,Type,Event,Value,Detail,Detail2
1931,design,log,
#design: #exp: Two_squares
#design: block_cnt,block_id,trial_cnt,trial_id
1931,design,logged,
1931,Experiment,started
1932,Stimulus,presented,1
1952,Stimulus,presented,2
1953,stderr,received,'Traceback (most recent call last):'
1954,stderr,received,'  File "D:\\UPcite_learning material\\Programming\\Assignments\\Week-2\\Exercises\\launching.py", line 39, in <module>\n    square_left.move(300, 0)\n    ~~~~~~~~~~~~~~~~^^^^^^^^'
1954,stderr,received,'TypeError: Visual.move() takes 2 positional arguments but 3 were given'
